### ISSUE TITLE
Is this layer updated?

### ISSUE THREAD

**Issue by koansoftware** [toradex/meta-toradex-tezi#2]
Is this layer tested and working with the latest Toradex BSP 5 or 6 ?
In the [README](https://github.com/toradex/meta-toradex-tezi#readme) I see references to branch: rocko

**Comment by escherstair** [comment]
I think that at least [kirkstone-6.x.y branch](https://github.com/toradex/meta-toradex-tezi/tree/kirkstone-6.x.y) is updated.
Bu the documentation in README is not.
Can @MaxKrummenacher or @hiagofranco take care of it?

**Comment by hiagofranco** [comment]
@escherstair @koansoftware: Sorry for the delay, I didn't see your comment.
This layer is updated and working for kirkstone, I will update the README. 
This GitHub repo is just a mirror of our internal GitLab, that's why I didn't see it earlier.

**Comment by hiagofranco** [comment]
README updated:

- https://github.com/toradex/meta-toradex-tezi/commit/7549a47f6d8e8474a281d62e797d7e561ae56184
- https://github.com/toradex/meta-toradex-tezi/commit/c21661f194fc0ffef452951466ebf9504b1b4373

**Comment by escherstair** [comment]
Hi @hiagofranco 
maybe the default branch of this repos hould be changed into [kirkstone-6.x.y](https://github.com/toradex/meta-toradex-tezi/tree/kirkstone-6.x.y).
At the moment is dunfell-5.x.y

**Comment by hiagofranco** [comment]
Hi @escherstair, we changed the default to kirkstone-6.x.y.
